### ISSUE TITLE
Channel-Ids

### ISSUE THREAD

**Issue by zauguin** [lightningnetwork/lightning-rfc#101]
I think the current construction of channel ids might be hard to extend beyond the bitcoin blockchain.
Maybe the current information could be hashed and a prefix of this hash used as transaction id, so that later an additional blockchain identifier could be added.

**Comment by rustyrussell** [comment]
Marcel Krüger <notifications@github.com> writes:
> I think the current construction of channel ids might be hard to extend beyond the bitcoin blockchain.

True.

> Maybe the current information could be hashed and a prefix of this
> hash used as transaction id, so that later an additional blockchain
> identifier could be added.

A channel-id is explicitly useful in a way a hash is not: it uniquely
identifies a bitcoin transaction.

For a different chain, you're going to have different identifiers.
That's OK: the announcement messages et al will need to be different
anyway.

AFAICT there should be some available compact identification in anything
which uses a blockchain.  Even if someone uses a central authority it
should still create canonical identifiers.

Cheers,
Rusty.
