### ISSUE TITLE
Removing the disconnect-on-warning

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lightning-rfc#1072]
I saw some users complaining that their lnd node is disconnecting a CLN node because the CLN node sent a warning "too many channel announcements with funding tx already spent, please check your bitcoin node". While maybe the underlying issue should be fixed, ISTM we should remove the "a recipient of a warning MAY disconnect" thing. The sender of the warning has more context about whether its a big deal or not, so we should leave it up to them to disconnect or not.

**Comment by vincenzopalazzo** [comment]
>a recipient of a warning MAY disconnect

yes I agree there is no point to have a warning if we do disconnect, it is an error at this point, IMHO the warning should not impact the close of a channel, in any case (maybe?)
