### ISSUE TITLE
moving out from libera and making a matrix channels

### ISSUE THREAD

**Issue by vincenzopalazzo** [lightningnetwork/lightning-rfc#1102]
We found out that the libera bridge is not available anymore (for now)
 https://matrix.org/blog/2023/08/libera-bridge-disabled/ on matrix.

But people that are using Element are still able to chat with each other.

So I just found out yesterday when on an IRC channel I was able to chat with @TheBlueMatt 

So, we can discuss if we want to open a matrix channel or keep the matrix channel that 
we have (with the dead libera bridge) and then in 6 months, we see if things are changed.

If not we try to move somewhere else due not the accessibility of IRC that for someone is a problem

**Comment by devrandom** [comment]
+1

**Comment by martindale** [comment]
+1
