### ISSUE TITLE
BOLT #3: missing witnessScript in witness of commitment transaction

### ISSUE THREAD

**Issue by yanxuebing** [lightningnetwork/lightning-rfc#125]
according to BIP141, 

> If the version byte is 0, and the witness program is 32 bytes:
> 
> - It is interpreted as a pay-to-witness-script-hash (P2WSH) program.
> - The witness must consist of an input stack to feed to the script, followed by a serialized script (witnessScript).
> - The witnessScript (≤ 10,000 bytes) is popped off the initial witness stack. SHA256 of the witnessScript must match the 32-byte witness program.
> - The witnessScript is deserialized, and executed after normal script evaluation with the remaining witness stack (≤ 520 bytes for each stack item).
> - The script must not fail, and result in exactly a single TRUE on the stack.

the last item of the witness data should be witnessScript,  i.e. \<2 \<key1\> \<key2\> 2 OP_CHECKMULTISIG\> in serialized form.

**Comment by sstone** [comment]
See https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#use-of-segwit

"...the last item on the witness stack must be the actual script that was used to generate the P2WSH output that is being spent. This last item has been omitted for brevity in the rest of this document."

**Comment by yanxuebing** [comment]
@sstone thanks, that's fine, I'm closing this issue.
