### ISSUE TITLE
Value of dust-limit-satoshis for the closing transaction

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lightning-rfc#128]
Since both nodes may choose a different value for `dust-limit-satoshis` (say `dust-limit-a` and `dust-limit-b`), I think we need to specify which one is to be used for the closing transaction in a mutual close scenario.

This is definitely a corner case, but it still can happen with `channel-reserve-satoshis` >> `dust-limit-satoshis` if we close a channel shortly after creation.

I think using `dust-limit-a` for the output going to A and `dust-limit-b` for the output going to B would make sense, but it might be easier to just use min( `dust-limit-a`, `dust-limit-b`) or max( `dust-limit-a`, `dust-limit-b`).

What do you guys think?

Cheers,

Pierre

**Comment by rustyrussell** [comment]
Pierre-Marie Padiou <notifications@github.com> writes:
> Since both nodes may choose a different value for `dust-limit-satoshis` (say `dust-limit-a` and `dust-limit-b`), I think we need to specify which one is to be used for the closing transaction in a mutual close scenario.
>
> This is definitely a corner case, but it still can happen with `channel-reserve-satoshis` >> `dust-limit-satoshis` if we close a channel shortly after creation.
>
> I think using `dust-limit-a` for the output going to A and `dust-limit-b` for the output going to B would make sense, but it might be easier to just use min( `dust-limit-a`, `dust-limit-b`) or max( `dust-limit-a`, `dust-limit-b`).
>
> What do you guys think?

Great question!

If A lets B choose the dust limit, there's a potential for an
unrelayable transaction (too low), or funds wasted on miners (too high).

At its root, this is a fundamental disagreement: if A considers its
output above the dust limit (ie. "Give me my money!") and B considers
A's output below the dust limit (ie. "No, that won't propagate!"), they
*cannot* mutual close.

Thus the simplest solution is to allow breakdown naturally:

        The sender MUST set `signature` to the Bitcoin signature of the
        close transaction with the node responsible for paying the
        bitcoin fee paying `fee-satoshis`, without populating any output
        which is below its own `dust-limit-satoshis`.  The sender MAY also
        eliminate its own output from the mutual close transaction.

        The receiver MUST check `signature` is valid for either the close
        transaction with the given `fee-satoshis` as detailed above and
        its own `dust-limit-satoshis` OR that same transaction with the
        sender's output eliminated, and MUST fail the connection if it
        is not.

Note that we might as well let a node eliminate its own transaction
anyway: dust-limit-satoshis might be lower than the economics of the
output.

Thoughts?
Rusty.

**Comment by pm47** [comment]
> there's a potential for an unrelayable transaction (too low), or funds wasted on miners (too high)

Right, of course! With that in mind my initial proposal doesn't really make sense at all.
