### ISSUE TITLE
Specification for invoice

### ISSUE THREAD

**Issue by EmelyanenkoK** [lightningnetwork/lightning-rfc#155]
Clearly defined invoice format is crucial for compatibility of different LN software. Thus it should be added to LN specification.
As I understand lnd, eclair and lightning-c already propose invoice formats, so I encourage @pm47, @cdecker and @rustyrussell to colloborate and create unified standart.

**Comment by bgorlick** [comment]
I completely agree -- I was speaking with Christian Decker about the same thing this morning. I would be willing to volunteer helping with the spec.

**Comment by cdecker** [comment]
@rustyrussell has started drafting an invoice format that might address the need to communicate the necessary payment information from a potential recipient to the sender. It includes the payment info such as the recipient's address, the amount and the payment hash. It also adds description and signature fields, which in conjunction with the secret are a proof-of-payment and could eventually become enforceable. And finally it allows for custom tag fields that can be used for other purposes (machine readable invoice ids, ...)

The proposal can be found here: https://github.com/rustyrussell/lightning-payencode

Feel free to discuss either here or on the mailing list :wink:

**Comment by rustyrussell** [comment]
Great minds think alike!  We had discussed this long ago and never actually done anything...

**Comment by pm47** [comment]
This was closed with #183.
