### ISSUE TITLE
minimum_depth field missed in open_channel message

### ISSUE THREAD

**Issue by EmelyanenkoK** [lightningnetwork/lightning-rfc#157]
While in __Requirements__ we have sentence: 
> The sender SHOULD set `minimum-depth` to an amount where the sender considers reorganizations to be low risk.

message description actually doesn't contain `minimum-depth` field.

I propose to add `minimum-depth` field to the end of message, thus it should not broke current implementation since basic policy for reading message: "read exactly number of bytes you need and drop residue". However it will be kind of ugly.

**Comment by rustyrussell** [comment]
Thanks!  I've simply proposed its removal, since we removed the field quite a while ago :)

See #162
