### ISSUE TITLE
Protect against last hop detection via timelocks

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#185]
Currently the recipient can be guessed by the second to last hop due to the short timelock on the HTLC, i.e., it is not plausible that this is just an intermediate hop since the timelock cannot further be reduced. We discussed adding a random offset to the CLTV timelocks in order to avoid this sort of detection. This can further be strengthened by computing an appendix/shadow route to the actual route of random length, and offsetting all CLTVs by the sum of CLTV values. It is still unclear whether the sender or the recipient should be the one computing the shadow route.

**Comment by pm47** [comment]
Related to this [discussion on the mailing list](https://lists.linuxfoundation.org/pipermail/lightning-dev/2016-March/000452.html)
