### ISSUE TITLE
Forget channels that have not received an update for x hours

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#186]
We currently have no good way of forgetting really old channels/nodes. By having nodes forget channels that they've not heard about in the last `n` hours (or similar) we can prune the channel graph easily, by putting a little bit more load on the network. I'd suggest having nodes issue a `channel_update` `n-1` hours after the last update, which should provide ample time for the update to propagate. If nothing changed the update should just resend the previous update, with the current timestamp.

**Comment by rustyrussell** [comment]
Christian Decker <notifications@github.com> writes:
> We currently have no good way of forgetting really old channels/nodes. By having nodes forget channels that they've not heard about in the last 6 hours (or similar) we can prune the channel graph easily, by putting a little bit more load on the network. I'd suggest having nodes issue a `channel_update` `n-1` hours after the last update, which should provide ample time for the update to propagate. If nothing changed the update should just resend the previous update, with the current timestamp.

What if the channel map actually ends up static?  Broadcasts like that
would just be noise.

We can spot if channels close, is that enough for now?

**Comment by cdecker** [comment]
So far we have two ways of detecting closed/unavailable channels:

 - Funding output gets spent, by watching the blockchain we should be able to see them
 - Disable message by one of the endpoints, only disables one side of the channel, but should be sufficient to not route through the node that disappeared.

Both of these mechanism require some action by the endpoints of the channel. My fear is that we'll accumulate channels, and consider them open, through events in which both endpoints disappear, and the channel remains open but unavailable. The proposal is more of a passive fallback to clear out really old and outdated channels.

It comes at a certain cost, sending some messages just to keep a channel from being dropped from the topology, but we can tweak the interval to something reasonable. I was thinking once a day, and @pm47 was suggesting once a week.

**Comment by rustyrussell** [comment]
On call, we agreed that 2 weeks was the arbitrarily-chosen but already-existing value (for adjustment changes).
