### ISSUE TITLE
Remove public keys from `channel_announcement` message

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lightning-rfc#187]
Instead, use key recovery based on the signatures (like in #183) to save space.

We would save 4*33 - 1 byte (4 * two "recovery bits") = 131 bytes.

**Comment by cdecker** [comment]
Can we squash the recovery bits into a single byte? That way we would have the nice 128 byte alignment :wink:

**Comment by rustyrussell** [comment]
Defer to 1.1, but @cdecker points out we should move features before keys in case we want to eliminate it later.

**Comment by cdecker** [comment]
Feature bitmap has been moved, giving us the flexibility once we decide that we want to do this.

**Comment by pm47** [comment]
Will switch to Schnorr instead.
