### ISSUE TITLE
Add description field to update_add_htlc message

### ISSUE THREAD

**Issue by BitfuryLightning** [lightningnetwork/lightning-rfc#189]
Add some text field to allow sending some additional information with payment. 
Currently, this suggestion is not very useful because some communication between sender and receiver is
required to share rhash. May became useful for onion encoded payments when there are no
prior communication between sender and receiver.

**Comment by rustyrussell** [comment]
We already have space in the onion itself for extra messages, which is ideal for this, right?

**Comment by Roasbeef** [comment]
Yep, the extra space in the onion messages, or signalling to the final node that it should consume the additional payloads in the packet should be sufficient. 

With that said, I think this issue can be closed?

**Comment by cdecker** [comment]
Yep, I think we should definitely not add a cleartext field that is seen by all nodes on the route, it just creates privacy leaks.

I'd like to wait for feedback from @sstone or @pm47 before closing this.

**Comment by pm47** [comment]
I agree with what was said above, I think the current construct already has everything in place to address this use case if needed.

**Comment by cdecker** [comment]
Ok, I'll close this for now, deferring any payment specific information to the onion specification.
