### ISSUE TITLE
BOLT 4 : channel_id

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#195]
Is BOLT 4 `channel_id` (type: `per_hop`) same as BOLT 7 `short_channel_id` ?

**Comment by rustyrussell** [comment]
ueno <notifications@github.com> writes:
> Is BOLT 4 `channel_id` (type: `per_hop`) same as BOLT 7 `short_channel_id` ?

Yes!

I've created a PR (#196) to fix this.

Thanks!
Rusty.
