### ISSUE TITLE
Pick a licence for the specs

### ISSUE THREAD

**Issue by josephpoon** [lightningnetwork/lightning-rfc#2]
CC-BY?
GNU FDL?
WTFPL?

**Comment by Roasbeef** [comment]
My vote is for the [WTFPL](http://www.wtfpl.net/) 🙌🏾. 

![WTFPL](http://www.wtfpl.net/wp-content/uploads/2012/12/wtfpl-strip.jpg)

**Comment by cdecker** [comment]
I quite like CC-BY but I have no idea of the implications :-)

**Comment by rustyrussell** [comment]
Joseph Poon <notifications@github.com> writes:
> CC-BY?
> GNU FDL?
> WTFPL?

CC-BY would be my default guess, but I'll ask People Who Know This Stuff
and see if there's some reason to prefer something else here.

Cheers,
Rusty.

**Comment by harrycheng8** [comment]
Duplicate of #
