### ISSUE TITLE
Clarify that type is not unique

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lightning-rfc#202]
I assumed that type was unique to each message, but now I see that both ping and final_incorrect_cltv_expiry have the same type.

**Comment by cdecker** [comment]
Yes, they are used in different contexts: one is a wire message and the other one is an error message wrapped in an error reply. I think it shouldn't be a huge problem and honestly I wouldn't know where to specify these potential collisions.

**Comment by ysangkok** [comment]
Okay, I understand

**Comment by cdecker** [comment]
Sorry, didn't want to sound discouraging :-) Do you know a good place to add this clarification. The onion routing spec in the introduction of errors seems like the best place.

**Comment by ysangkok** [comment]
Yeah that would make sense. But now that you explained it , it makes a lot
of sense. I hadn't looked at the onion protocol because it is not relevant
to our use in Electrum , so I just assumed the output of the protocol
message extractor meant it was invalid. I don't think a change is strictly
necessary.

**Comment by cdecker** [comment]
No no, you certainly have a point, I'll create a PR with the clarification. Just wondering: are you integrating LN with Electrum?

**Comment by ysangkok** [comment]
Yes, I am working on exactly that. :smile: There is most likely going to be an Electrum Lightning server that connects to the rest of the network, and the user could initially only use the Electrum Lightning servers, they would of course provide HTLC's and be relatively well connected.

**Comment by cdecker** [comment]
Great, looking forward to testing your implementation. I tried to address the clarification issue in #207, does that sound reasonable?

**Comment by ysangkok** [comment]
Yes, sounds good.
