### ISSUE TITLE
Include current `perCommitmentPoint` in `ChannelReestablish`

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#209]
Current local channel state may be completely lost at any moment, this is most relevant to mobile devices (destruction, loss, etc) but can happen on any setup. It would be nice to have a way to claim at least some of the remaining channel funds in such a situation.

Having current `perCommitmentPoint` included in `ChannelReestablish` would allow for the following scheme:

- save static channel parameters once a new channel is created (on a backup server for example, linked to a hash of BIP 32 master key so user can retrieve it later using a mnemonic code)
- retrieve this info on a new device after an old one is lost
- reestablish a connection, wait for incoming `ChannelReestablish`, then send and `Error` and wait for a current commit to be published, then use `perCommitmentPoint` and saved static channel parameters to claim a P2WPKH output.

HTLC outputs can't be claimed but this may be okay in a majority of cases as mobile device is much more likely to get lost when it's in a steady state (has no in-flight HTLCs) anyway.

**Comment by ysangkok** [comment]
Why not just store the current `per_commitment_point` on that server? If the spec starts catering to malfunctioning clients (surely it is malfunctioning if it loses the current `per_commitment_point`, right?), where do we stop? And how should a node react if it observes an incorrect `per_commitment_point`, having NOT forgotten the correct `per_commitment_point` ifself?

**Comment by btcontract** [comment]
> Why not just store the current per_commitment_point on that server? 

it will require an additional server call on each commit (which occasionally may not be recorded due to network conditions and so on). Also, unlike "revoked tx watchdog" server case, this will require some form of accounting i.e. which _last_ `per_commitment_point` belongs to whom, this is bad for privacy. 

> And how should a node react if it observes an incorrect per_commitment_point, having NOT forgotten the correct per_commitment_point ifself

my guess it client should close a channel unilaterally in this case to discourage sending outdated or irrelevant points. 

> If the spec starts catering to malfunctioning clients (surely it is malfunctioning if it loses the current per_commitment_point, right?), where do we stop?

spec catering to malfunctioning clients does not seem bad to me. LN on mobile devices would be nearly unusable otherwise.

**Comment by rustyrussell** [comment]
OK, so you would send your *own* perCommitmentPoint.  I think this would be sufficient for non-HTLC recovery, but I'd need to double-check.  I don't hate the idea, however.

**Comment by Roasbeef** [comment]
> Also, unlike "revoked tx watchdog" or "save static params once" server cases, this will require some form of accounting i.e. which last per_commitment_point belongs to whom, this is bad for privacy.

The server can just use the exact same protocol as the existing watchers (or WatchTower as Tadge likes to call them) on the network.

Stepping back a bitt, this isn't incentive compatible...nor is our current channel reestablishment scheme either. If upon connection, a node detects that another has lost some (or all of its state), then it can take advantage of the connecting node by feeding it invalid or stale data. As an example, consider the following scenario: 
  * Alice and Bob have a channel together
  * Bob loses as his data (didn't have back up servers, didn't use any watchtowers, etc)
  * Bob re-connects to Alice (assume we're using the scheme suggested), Alice gives her point.
  * Bob tries to make Alice fail the channel, Alice realizes something is up, and concludes that Bob has lost data (she could, for example try to violate a channel constraint, which _should_ cause him to fail the channel, but he doesn't).
   * Alice then broadcasts _any_ prior state where she was better off, knowing that Bob _may_ not have any recourse. 

In cases where Bob recovers partial information, it's still possible for Alice to _trick_ Bob using her channel re-establishment message that they're on a state _prior_ to the latest. In this position, once Bob obtains a commitment (which he has actually _already_ revoked), if he broadcast that commitment on-chain, then Alice can take all the funds as the contract has been violated (but Alice didn't have enough data to recognize that).

**Comment by btcontract** [comment]
> The server can just use the exact same protocol as the existing watchers (or WatchTower as Tadge likes to call them) on the network.  

Can you please elaborate on this? The way I see it, saving latest channel states on a server would require an ordering info (which state is the last one) and some stable identifier across all the states (who's the owner) and thus a sort of payment history is formed which is not desired. Sending a revoked commit info to WatchTower requires none of these.

> Bob tries to make Alice fail the channel, Alice realizes something is up, and concludes that Bob has lost data (she could, for example try to violate a channel constraint, which should cause him to fail the channel, but he doesn't).
> Alice then broadcasts any prior state where she was better off, knowing that Bob may not have any recourse.

Yes, sorry for not mentioning this right away but this scheme does require a client to constantly use an external WatchTower before channel state is lost. I believe this is a plausible assumption for mobile devices at least. A wallet of mine will always have some WatchTower, either a default one or user provided.

In general, none of this is ideal of course. Alice can just do nothing at all on receiving an `Error` and that's that. But this is perhaps better than nothing, Alice may have reasons to play nice knowing she can't trick Bob (he does no accept anything but `ChannelReestablish` and then sends an `Error`, WatchTower is in place).

**Comment by rustyrussell** [comment]
Olaoluwa Osuntokun <notifications@github.com> writes:
> Stepping back a bitt, this isn't incentive compatible...nor is our current channel reestablishment scheme either. If upon connection, a node detects that another has lost some (or all of its state), then it can take advantage of the connecting node by feeding it invalid or stale data. As an example, consider the following scenario: 
>
>   * Alice and Bob have a channel together
>   * Bob loses as his data (didn't have back up servers, didn't use any watchtowers, etc)
>   * Bob re-connects to Alice (assume we're using the scheme suggested), Alice gives her point.
>   * Bob tries to make Alice fail the channel, Alice realizes something is up, and concludes that Bob has lost data (she could, for example try to violate a channel constraint, which _should_ cause him to fail the channel, but he doesn't).
>    * Alice then broadcasts _any_ prior state where she was better off, knowing that Bob _may_ not have any recourse. 

We could actually include sufficient previous information to disallow
this (ie. sufficient previous revocation preimages).

One answer is the WatchTower idea (cool name BTW).  I've previously
suggested that we hand peers a data blob, which it then sends back when
we reconnect; this could contain encrypted state of any peers, as a kind
of emergency backup.

But I agree that this isn't 1.0 material...

**Comment by rustyrussell** [comment]
Deferring for 1.1.  @Roasbeef promised to ping @adiabat to see where we are with WatchTower...

**Comment by rustyrussell** [comment]
OK, so as per our meeting: https://docs.google.com/document/d/1K4QnOy0koZ_ndKltledRrvN-Zu4JDFXT8S9GGxFwjdw/edit?usp=sharing

We don't have a good "restore from backup, how do I know I'm stale" check for 1.0.  This isn't perfect, but it's simple and important.

Nonetheless, the spec is in freeze, so this is best added as an option to avoid breaking compat again.  I will prepare the spec update...
