### ISSUE TITLE
BOLT#11: Single or double hash of data?

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lightning-rfc#223]
The requirements for the data part of the payment invoice reads:
"A writer MUST set signature to a valid 512-bit secp256k1 signature of the double SHA2 256-bit hash of the Human Readable Part concatenated with the Data Part and zero bits appended to the next byte boundary, with a trailing byte containing the recovery ID (0, 1, 2 or 3)."

However, trying to decode the examples created by @rustyrussell, I can only make it verify by taking a single hash of the data. What is correct?

**Comment by rustyrussell** [comment]
Excellent catch.  It seems that single sha256 is the norm (and in fact, the default for the python secp256k1 library). And AFAICT, bitcoin core's signmessage uses that too.
