### ISSUE TITLE
BOLT-11: Max size of description (d) field

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lightning-rfc#236]
I think we should set a max allowed length for the description field, as it is now not specified. As of  now we must support strings of any size, which is probably not necessary.

I suggest 1024 characters/bytes, I think that should be enough.

**Comment by rustyrussell** [comment]
Actually, the limit is 640 characters.  That's because `data_length` is 10 bits long, and counts 5 bit values.  So we can have 5*1024 bits == 640 bytes.

**Comment by halseth** [comment]
Thanks, you are right! Did not think about that 👍
