### ISSUE TITLE
Byte-order of chain_hash in messages

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#237]
We did not specify the byte-order of the chain_hash field
in the `open_channel` and the `channel_announcement` messages. While
testing integration I noticed that the three implementations disagree
about the ordering:

 - c-lightning and eclair both use the reversed order that bitcoin
   uses internally, i.e., interpreting the hash as a little-endian
   number.
 - lnd uses the non-reversed byte-order that is directly produced by
   the hashing function.

I think both have their merits, however we need to agree on which
order to use, otherwise we'll be unable to open a channel, or exchange
gossip.

**Comment by rustyrussell** [comment]
Crap.  BOLT #1:

    All data fields are big-endian unless otherwise specified.

Looks like c-lightning and eclair need a fix!

**Comment by Roasbeef** [comment]
The genesis hash is a hash, why is it subject to the endian rules governing byte ordering for integers? 

The output from Bitcoin related RPC calls always reverse the bytes of any hashed items such as txid's etc. If one were to take the txid outputted and attempt to craft a transaction using the hash raw without reversing it, then that transaction would be invalid. 

The non-reversed byte-order is the correct value as this ordering is what Bitcoin uses on the wire protocol to refer to header hashes, txids, etc.

**Comment by rustyrussell** [comment]
@roasbeef SHA256 is big endian.  Bitcoin's weird on-wire rules for transmission have been roundly rejected for block hashes, in particular: see every block explorer ever, and the RPC interface.
