### ISSUE TITLE
BOLT#4 : 256 length Test Vector

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#241]
> The node SHOULD set pad such that the failure_len plus pad_len is equal to 256.

I'm debugging our LN node.   
Maybe, current [Returning errors](https://github.com/lightningnetwork/lightning-rfc/blob/5a60b0317402081ab075c1d02081b72d52e312ee/04-onion-routing.md#returning-errors-1) is 128 length.  
` payload = 00022002007e000000000000000...`

Is there 256 length Test Vector ?

**Comment by rustyrussell** [comment]
Yep, see #231

**Comment by nayuta-ueno** [comment]
Thank you!
Close this issue.
