### ISSUE TITLE
BOLT-03: Funding transaction change amount is... difficult

### ISSUE THREAD

**Issue by jimpo** [lightningnetwork/lightning-rfc#249]
[BOLT-03, Appendix C: Funding Transaction Test Vectors](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#appendix-c-funding-transaction-test-vectors), provides an expected funding transaction that should be generated by BOLT-compatible implementations. The transaction has a total size of 232 bytes, with no witness data, giving it a total weight of 928. The fee on the transaction is 13920 satoshis. So the fee exactly matches the transaction weight at the specified fee rate of 15 satoshis/byte.

The problem is that the scriptSig in the funding transaction has a signature that is only 72 bytes as opposed to the maximum possible 73 bytes. So when a wallet is creating the transaction, it needs to estimate the transaction size before it can be signed, and it is common to generate the fee estimate assuming that signatures will be the maximum possible 73 bytes. Basically, the transaction should probably have been generated with a fee of 13980 satoshis instead of 13920, and wallets using this fee estimation strategy will not end up with a matching funding transaction.

**Comment by sstone** [comment]
This transaction is an input to the test, not an output that needs to be checked: you don't need to ask your wallet to recreate this exact same funding transaction, instead you assume that this is the funding transaction, and for each test create commitment and HTLC transactions and check that they match the test vectors.

**Comment by Roasbeef** [comment]
Seems this has been resolved, closing.
