### ISSUE TITLE
Which `per_commitment_point` should I use ?

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#251]
Which `per_commitment_point` should I use at `remotekey` and `remote_delayedkey` ?

Test Vector's localkey is `local basepoint` & `local per_commitment_point`.
So, I think remotekey is `remote basepoint` & `remote per_commitment_point`, but c-lightning uses `local basepoint` & `remote per_commitment_point` and `remote basepoint` & `local per_commitment_point` in script (maybe) ...

Please write about `per_commitment_point` like [revocationkey](https://github.com/lightningnetwork/lightning-rfc/blob/9073a5f3dee808d6a71f0b9d1ac5663c033b8755/03-transactions.md#revocationkey-derivation).

**Comment by rustyrussell** [comment]
So the per_commitment_point belongs to the commitment transaction; my commitment transaction always uses my per_commitment_point, and generates localkey from local basepoint, remote key from remote basepoint.

**Comment by nayuta-ueno** [comment]
Thank you !
