### ISSUE TITLE
No melody of the theme song provided

### ISSUE THREAD

**Issue by kristoffernolgren** [lightningnetwork/lightning-rfc#270]
I like the lyrics, but a melody would be nice

**Comment by cfromknecht** [comment]
Believe it's supposed to be: https://www.youtube.com/watch?v=H-kL8A4RNQ8

**Comment by rustyrussell** [comment]
I believe that reproducing the Greased Lightning melody would violate copyright, unless we received a license from the copyright holders.  Which seems unlikely...
