### ISSUE TITLE
[Q] How can I monitor a transaction with `payment_preimage`?

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#276]
question:

1. `A` send `update_add_htlc` to `C` (`C` has preimage).
2. `commitment_signed` and `revoke_and_ack` are exchanged in `A--B` and `B--C`.
3. `C` don't send `update_fulfill_htlc` and disconnect.
4. `B` send latest `B-C` commitment transaction (unilateral close).
5. `C` send [witness `<remotehtlcsig> <payment_preimage>`](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md#offered-htlc-outputs) to redeem Offered HTLC.
```
A (offered) ---> (received) B (offered) ---> (received) C
```

Can `B` monitor `5`'s transaction to get `<payment_preimage>` for `A-B` HTLC ?
I can't calculate this TXID for `getrawtransaction` ...

**Comment by pm47** [comment]
`B` **has** to do that, otherwise it would lose money in this scenario.

This topic is covered in [BOLT 5](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md#on-chain-htlc-output-handling-their-offers).

**Comment by nayuta-ueno** [comment]
Thank you !
Give me some time to understand...

**Comment by nayuta-ueno** [comment]
I read "Their Offers".

`A (offered) ---> (received) B (offered) ---> (received) C`

In this case, both nodes HTLC are `irrevocably committed`.
`B`(`C`'s side) send commitment transaction, so `C` spend `convenient address`.

If `B` wishes to get `C`'s TXID for extract `payment_preimage`, will `B` use a tool like BlockExplorer ("has to do that" means "`C`'s TXID cannot calculate") ?

**Comment by btcontract** [comment]
@nayuta-ueno you can listen to every incoming transaction using ZMQ API and check if it spends any of commit tx's outputs. Or even try to extract a preimage from every incoming transaction and update respected LN payment in a db if matching hash is found.

**Comment by nayuta-ueno** [comment]
@btcontract thank you!
I think ZMQ API behave like `inv` message, so I'll take your second idea if need.
