### ISSUE TITLE
Note: we should not ignore channel_updates when coming from errors.

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lightning-rfc#282]
We can get them for private channels in that case when used eg. with r hints from bolt11.

**Comment by pm47** [comment]
My bad, this is already handled in BOLT 7:
> A node MAY still create a channel_update to communicate the channel parameters to the other endpoint, even though the channel has not been announced, e.g., because the announce_channel bit was not set. For further privacy such a channel_update MUST NOT be forwarded to other peers. Note that such a channel_update that is not preceded by a channel_announcement is invalid to any other peer and would be discarded.

I think this can be closed.
