### ISSUE TITLE
about `payment revocation`

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#290]
What is [`payment revocation`](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md#requirements-6) at case3 and case4 ?
to_local output and HTLC-timeout/success are "`using the revocation key`".

**Comment by rustyrussell** [comment]
ueno <notifications@github.com> writes:
> What is [`payment revocation`](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md#requirements-6) at case3 and case4 ?
> to_local output and HTLC-timeout/success are "`using the revocation key`".

Yes, good catch!  "payment revocation" should be "revocation key".

But we have several PRs cleaning this right now, I'll leave this open:
if they don't fix this, I will do it separately.

Thanks!
