### ISSUE TITLE
Assisted route for payment request without amount

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#296]
Looks like it is currently impossible to add an assisted route to a payment request without amount (donation case) since every `r` tag entry must contain a pre-calculated `fee` which is "the total fee required to use that channel to send `amount` to the final node", but without amount there is nothing to pre-calculate on.

**Comment by rustyrussell** [comment]
Anton Kumaigorodski <notifications@github.com> writes:
> Looks like it is currently impossible to add an assisted route to a payment request without amount (donation case) since every `r` tag entry must contain a pre-calculated `fee` which is "the total fee required to use that channel to send `amount` to the final node", but without amount there is nothing to pre-calculate on.

Crap.  Good point!  I was trying to avoid two fields (base + proportional).

It was also a poor for if you're fuzzing the amount, but you can just
scale the fee in that case and it will still work (though, if there's a
base fee you're now overpaying).

Two possibilties:

1.  Change spec.  I don't think anyone *uses* r at the moment, we could
    fix it to have both fields.

2.  Use a nominal amount (1M millisatoshi?) to calculate fee if amount
    isn't specified?

Cheers,
Rusty.

**Comment by btcontract** [comment]
having base + proportional makes a field look more like `channel_update` and thus seems like a cleaner solution, but I'm no expert of course.
