### ISSUE TITLE
BOLT7 `htlc_expiry`

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#325]
Is [minimal value for `htlc_expiry` in BOLT7](https://github.com/lightningnetwork/lightning-rfc/blob/faee5ab6e7e363469715354d8b50a038fc38bf61/07-routing-gossip.md#the-channel_update-message) same as payee's minimal `cltv_expiry` ?
This word only appears here.

**Comment by rustyrussell** [comment]
Good spotting!  Yes, it's cltv_expiry.  I will fix.

**Comment by nayuta-ueno** [comment]
Thanks !
