### ISSUE TITLE
BOLT#7: htlc_minimum_msat of remote?

### ISSUE THREAD

**Issue by halseth** [lightningnetwork/lightning-rfc#328]
During channel opening, the remote specifies the minimum HTLC value it is willing to accept: https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#the-open_channel-message

If I'm not mistaken, then when announcing this parameter to the network, the node will announce _the remote's_ minimum HTLC value in its `ChannelUpdate`: https://github.com/lightningnetwork/lightning-rfc/blob/master/07-routing-gossip.md#the-channel_update-message

The requirements for `ChannelUpdate` currently read: "It MUST set htlc_minimum_msat to the minimum HTLC value it will accept, in millisatoshi." Should this rather be something like "It MUST set htlc_minimum_msat to the minimum HTLC value the remote node is willing to accept, in millisatoshi, as expressed during channel opening"?

**Comment by pm47** [comment]
Hey Johan, I'm confused: this has been fixed in #287 (merged 2 days ago)

**Comment by halseth** [comment]
Aaah, I knew I had seen this being discussed somewhere! I must have had an outdated tab open, thanks!
