### ISSUE TITLE
Allow mutual close before `min_depth`

### ISSUE THREAD

**Issue by pm47** [lightningnetwork/lightning-rfc#335]
The spec is a little vague on this, but I don't see why we shouldn't allow it?

Currently eclair and lnd only allow an unilateral close before `min_depth`, not sure about c-lightning.

**Comment by Roasbeef** [comment]
`lnd` currently doesn't allow a cooperative close before `min_depth`. Agreed that there's no reason _not_ to. The fact that we currently don't is just an implementation detail.
