### ISSUE TITLE
feerate_per_kw unit is unspecified

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lightning-rfc#336]
feerate_per_kw is specifed as "feerate per 1000-weight" but never what unit "feerate" is...msat? sat? etc.

**Comment by cdecker** [comment]
This should be in satoshis / kw if I remember correctly.

**Comment by rustyrussell** [comment]
It's satoshi per kila-sipa.  Or, if you prefer, millisatoshi per sipa.

**Comment by rustyrussell** [comment]
It does say "(i.e. 1/4 the more normally-used 'fee rate per kilobyte')", which implies that it's in satoshi.

**Comment by TheBlueMatt** [comment]
Heh, I've never seen 'satoshi per kb' used...more commonly satoshi per vbyte, or Bitcoin Core's Bitcoin-per-kb. Either way should be clarified in the doc itself not just issue discussion :p.

**Comment by rustyrussell** [comment]
Yeah, this was written before vbyte vs weight thing was standard.  vbyte should just die, of course.  Will add comment.
