### ISSUE TITLE
Rationale for max value of `funding_satoshis` in `open_channel` message

### ISSUE THREAD

**Issue by araspitzu** [lightningnetwork/lightning-rfc#353]
Hello I noticed in the [requirements](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements) of the peer protocol the max value of funding_satoshis MUST be set to less than 2^24, although the field in the message is capable of 2^64. Is it possible to add the rationale for this choice to the specification [rationale](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#rationale) ?

**Comment by cdecker** [comment]
This is a temporary measure, while the implementations are not yet considered stable. This is a self-imposed limit that can be lifted at any point in time, since it is enforced only by the two endpoints of a channel. I'll add this as a rationale to the document.
