### ISSUE TITLE
Minimum payment support / Optional tip

### ISSUE THREAD

**Issue by Richard87** [lightningnetwork/lightning-rfc#362]
Hi!

I would like to send an invoice on a minimum amount (0.97mBTC), but I would like to let the customer add a variable tip.

Thanks, Richard

**Comment by ZmnSCPxj** [comment]
BOLT 4 allows the payer to overpay up to twice the invoice amount:

> - if the amount paid is more than twice the amount expected: 
>   - SHOULD fail the HTLC.

(by implication, if the amount paid is not more than twice, should accept the HTLC)

Allowing payment up to twice the invoiced amount should be enough to cover the invoiced amount plus tip, as tips are usually in the range of 10% of the invoiced amount.

Note however that c-lightning at least does not support overpayment of invoices (it will reject attempts to specify exact value if the invoice indicates a value).

**Comment by Richard87** [comment]
Thanks :)
