### ISSUE TITLE
Exponentially decaying max acceptable payment fee

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#363]
When considering a payment route there should be some kind of fee filtering which arguably should not be linear but should depend on payment sum itself.

What if max acceptable fee to be derived by this formula: `max_fee = payment_sum_sat * (e ^ (-log(my-fee-base-sat, payment_sum_sat) )`

Suppose my node's `fee-base-sat = 10 SAT`, then:

- for a payment of `10 SAT`, max acceptable fee is `10 * (e ^ (-log(10, 10) )` = `3.67 SAT`
- for a payment of `100 SAT`, max acceptable fee is `100 * (e ^ (-log(10, 100) )` = `13.53 SAT`
- for a payment of `1000 SAT`, max acceptable fee is `1000 * (e ^ (-log(10, 1000) )` = `49.78 SAT`
- for a payment of `10000 SAT`, max acceptable fee is `10000 * (e ^ (-log(10, 10000) )` = `183.15 SAT`

**Comment by rustyrussell** [comment]
"What is an acceptable fee?" is an implementation q we don't address in the specs.  I think it depends on real world stats we don't have yet, though.
