### ISSUE TITLE
pong response time limit

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#373]
Is there a time limit between my node sending `ping` and receiving `pong` response from peer node?
If there is no time limit, should I not send the next `ping` until I receive `pong` response?

**Comment by cdecker** [comment]
The [spec](https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#requirements-2) doesn't really require a `ping` recipient to reply at all, but allows the `ping` sender to close the connection if a `pong` is not received in a reasonable timeframe.  Besides that I think you can send concurrent `ping`s without any problem, keeping in mind the flood limit of 30 seconds (which is also a bit fuzzy).

Notice also that a really large `ping` `num_pong_bytes`, we MUST ignore the `ping` and thus the sender will never receive a matching `pong`.

**Comment by nayuta-ueno** [comment]
Thank you for your reply.

> a really large ping num_pong_bytes, we MUST ignore the ping

Does this means `num_pong_bytes >= 65532` ?

**Comment by rustyrussell** [comment]
Yes, exactly.
