### ISSUE TITLE
BOLT 9: Endianness of feature bit array is ambiguous

### ISSUE THREAD

**Issue by jimpo** [lightningnetwork/lightning-rfc#424]
BOLT 1 specifies that all fields are big-endian unless otherwise specified, but c-lightning treats the feature bit vector as little-endian [here](https://github.com/ElementsProject/lightning/blob/2d919d56cb6097c753b534a2baf711631e39a18a/common/features.c#L17) (assuming I have read the code correctly). [lnd](https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go#L125) and [eclair](https://github.com/ACINQ/eclair/blob/da3eb3b9b2446b2bbe7df25d73693a092c16c691/eclair-core/src/main/scala/fr/acinq/eclair/Features.scala#L48) both treat it as big-endian. BOLT 9 is kind of ambiguous on this point.

**Comment by rustyrussell** [comment]
Will fix c-lightning...
