### ISSUE TITLE
Support for version and implementation advertising

### ISSUE THREAD

**Issue by gustavonalle** [lightningnetwork/lightning-rfc#430]
Currently nodes support advertising a color and a alias publicly, but there is no way to reliably detect the version and the implementation of the node, example ```/Eclair:0.2/```,```/lnd:0.4.1-beta/``` and so on.

Having the version is useful to detect and track interoperability issues between several implementations, instead of relying on pattern matching error messages and strings from other fields. 

It'd also give visibility of the popularity and usage breakdown among the several implementations in the wild.

Last but not least, the advertising of the version could be optional in case "security through obscurity" is desired.

**Comment by Roasbeef** [comment]
Nodes can already do this in their alias.

**Comment by gustavonalle** [comment]
My understanding is alias is a user supplied information for display/label purposes, and very few (or none) care to use the software implementation version in it.
I was referring to a a protocol level field akin to https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki

**Comment by rustyrussell** [comment]
We have explicit feature bits; we certainly hope they will be sufficient for compatibility.  Otherwise we risk "the Mozilla problem", see https://webaim.org/blog/user-agent-string-history/

**Comment by gustavonalle** [comment]
Browser user agents are indeed a mess. This could be avoided by preventing an unlimited, free form string and adding a stricter, pre-defined structure, e.g. ```implName:x.y.z``` 

And regarding feature bits, I agree they play a role in detecting and reacting to different capabilities for each node, but the idea of this proposal is merely providing something informative for tracking purposes, not to be used for any decision about routing or a way to send different messages based on different remote impl and version.

It's rather to answer question like, which github repo should I open an issue if the remote node is sending a malformed message? What is the most popular implementation? Is this bug of the remote peer a new one, or am I talking to an older version that hasn't upgraded yet?

**Comment by cdecker** [comment]
I briefly suggested adding the version into the alias, after terminating
that alias with 0x00 byte (which indicates to most string functions the
end of that string), however that must be gated behind a command line or
compilation flag, and as @rustyrussell points out c-lightning is already
announcing its version in the ping payload and the default alias if
compiled with `DEVELOPER=1`. I also don't feel comfortable broadcasting
implementation and version by default, and I found profiling nodes via
their default parameters sufficient for most debugging related
questions.

**Comment by rustyrussell** [comment]
We may come to regret this, but the consensus is that introducing such a feature would be very hard to later remove, as implementations come to "temporarily" depend on it and that never ends.
