### ISSUE TITLE
Gossip message to indicate that peer delays a payment

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#437]
There's a possible type of attack which was discussed previously here: https://github.com/lightningnetwork/lightning-rfc/issues/182#issuecomment-374958727

Suppose there's `Bob` -> `Alice` channel where `Bob` is sending an HTLC and `Alice` is a malicious node. The most insidious and at once most realistic `Alice` behavior would be to accept a payment, then just do nothing for as long as possible, then fail it to not let a peer close a channel uncooperatively because of expired HTLC.

`Bob` may use some kind of analysis to detect this malicious behavior over time and, say, start failing -> `Alice` payments right away but that would be a local knowldge while also letting everyone else know might be useful. Obviously `Bob` would have to prove that what he claims is true so he can include an _unsigned_ `commitTx` along with `(HtlcTimeoutTx, bobSig, aliceSig)` in a gossip message.

Having this data all the other nodes can get channel funding tx and related `peerNodeId`s by examining `commitTx` input and can verify that HTLC exists, spends from `commitTx`, is signed by both peers and is close to expiration point by examining `(HtlcTimeoutTx, bobSig, aliceSig)`. It would be up to other nodes on how to react to this.

This can be further extended by combining two events: gossip "complain" message and following uncooperative closing on-chain tx which contains a related payment as one of it's outputs. This would further indicate that `Alice` is malicious or buggy and appropriate measures could be taken.

**Comment by tyzbit** [comment]
Perhaps this could be remedied by using the penalty system outlined in my [Atlas](https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-June/001300.html) idea I discussed on the mailing list.
