### ISSUE TITLE
Extending an `OpenChannel` message to attach a payment request

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#450]
A nice way to set up a channel would be to open it and push a requested payment amount right away. `push_msat` already allows this but it's often not sufficient since a payee may need an additional info to link a pushed amount to a service it renders.

So what if `OpenChannel` message could be extended with an optional field to contain a payment request, and then a feature bit added to indicate support for opening a channel this way? Having a payment request at once gives payee all the info it needs as well as allows it to verify that `push_msat` amount is correct.

One issue I can think of is this requires trust since payee does not provide a preimage. One way to solve it would be to also extend an `AcceptChannel` to contain a signature of "this payment request is fulfilled if this channel funding transaction exists" statement.

**Comment by Roasbeef** [comment]
If the user first receives an invoice, tries that and it fails. Then they have all they need in order to actually use the push amount.
