### ISSUE TITLE
BOLT 2: chain_hash requirement for accept_channel?

### ISSUE THREAD

**Issue by matthias-g** [lightningnetwork/lightning-rfc#453]
In [02-Peer-Protocol](https://github.com/lightningnetwork/lightning-rfc/blob/e0c436bd7a3ed6a028e1cb472908224658a14eca/02-peer-protocol.md#the-accept_channel-message) the specification says, under `accept_channel` -> Requirements -> The receiver:
> if the `chain_hash` value, within the `open_channel`, message is set to a hash of a chain that is unknown to the receiver:
>     - MUST reject the channel.

To my understanding this should be a requirement for the `open_channel` message instead for the `accept_channel` message. The `chain_hash` value is not included in the `accept_channel` message and as the receiver of the `accept_channel` message is the sender of the `open_channel` message, this would be the same as the requirement for the `open_channel` message, that the sender
> MUST ensure the chain_hash value identifies the chain it wishes to open the channel within.

**Comment by rustyrussell** [comment]
Good catch, yes, it's in the wrong place....
