### ISSUE TITLE
Why is the DER encoded per_commitment_key 33 instead of 32 bytes?

### ISSUE THREAD

**Issue by renepickhardt** [lightningnetwork/lightning-rfc#457]
Looking at the source code of the implementations it is at every point where I looked a 256 bit pubkey which should be 32 bytes. 

I see that all over the spec the `per_commitment_key` is 33 bytes so I guess this must be true and not a typo. 

But where does the additional byte come from? 

I couldn't find anything about that in [BOLT2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md) where the term is being used first.

**Comment by halseth** [comment]
I believe it is using the compressed pubkey format: https://bitcoin.org/en/glossary/compressed-public-key :)
