### ISSUE TITLE
announcement_signatures timing

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lightning-rfc#468]
Currently, BOLT 7 states that you "MUST NOT send announcement_signatures messages until funding_locked has been sent" and also that you "SHOULD queue the channel_announcement message" once you've "sent AND received a valid announcement_signatures message".

In order to comply with the SHOULD on the announcement, you'd be forced to (at least temporarily) store the remote peer's announcement signatures somewhere that isn't your outbound channel_announcement queue so that you have them when you send your funding_locked and announcement_signatures as the remote peer wont send them again. If, instead, a node SHOULD wait until it has both sent and received a funding_locked to send an announcement_signatures, you would sidestep this requirement and be able to avoid any additional storage with both sides able to freely broadcast the channel_announcement.

It looks like at least c-lightning already does this, waiting until funding_locked on both sides to send its announcement_signatures, but this has the potential to violate the SHOULD and result in never announcing the channel. This is fine (and, hence, the proposed change is backwards-compatible-ish) as long as you can handle receiving a channel_announcement for your own channel and sending appropriate channel_update therafter, and eventually if clients start complying with the proposed change things will be simpler. What lnd does is less obvious from a quick grep.

**Comment by rustyrussell** [comment]
Looks like I misread the spec here, indeed :(

I assumed complete exchange of funding_locked predeeded exchange of announcement_signatures.  Which, as you say, is logical, but not spec compliant.  We would recover on reconnect, due to the retransmission requirements, but that's not a solution.
