### ISSUE TITLE
final_incorrect_htlc_amount data length is strange

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lightning-rfc#469]
final_incorrect_htlc_amount's data length is defined as taking the htlc value in msat and encoding it in a uint32_t instead of uint64_t. This is super weird as the value being encoded is uint64_t both in the update_add_htlc message and in the onion packet, so we're just throwing away precision and not even saving bytes on the wire. As far as I can tell lnd already implements this incorrectly and c-lightning doesn't do anything with the decoded error contents, so it'd be nice to just change it to a uint64_t and move on.

**Comment by rustyrussell** [comment]
Good catch!  As I think nobody parses this at the moment (I assume Eclair doesn't either?), we should fix it.  It comes from when we used u32 for htlc values, but that was changed well before 1.0 spec freeze.
