### ISSUE TITLE
BOLT2: both nodes send `update_add_htlc`

### ISSUE THREAD

**Issue by nayuta-ueno** [lightningnetwork/lightning-rfc#472]
Question

I want to know what kind of `committed_signed` packet should be created after both nodes send `update_add_htlc`.

[BOLT2: Normal Operation]
> Counter-intuitively, these updates apply to the other node's commitment transaction; the node only adds those updates to its own commitment transaction when the remote node acknowledges it has applied them via `revoke_and_ack`.

Maybe, I think that means above sentences have below meaning:

* `update_add/fulfill/fail/malformed/_htlc`
  * sender: change remote commitment_transaction
  * receiver: change own commitment_transaction
* `revoke_and_ack`
  * sender: change own commitment_transaction
  * receiver: change remote commitment_transaction
----
[BOLT2 Normal Operation example sequence](https://github.com/lightningnetwork/lightning-rfc/blob/0bb2739133a678498c6fd4e9241cd23eeefe8361/02-peer-protocol.md#normal-operation)

1. [A -->B]send `update_add_htlc`
2. [A -->B]send `update_add_htlc`
3. [B -->A]send `update_add_htlc`

```
At this time:
  * A have:
    * A's commitment transaction: HTLC No.3(unsign)
    * B's commitment transaction: HTLC No.1,2(unsign)
  * B have:
    * A's commitment transaction: HTLC No.3(unsign)
    * B's commitment transaction: HTLC No.1,2(unsign)
```

4. [A-->B]send `commitment_signed` (signature: B's commitment transaction(No.1,2 HTLC))
5. [B-->A]send `revoke_and_ack`

```
At this time:
  * A have:
    * A's commitment transaction: HTLC: No.1, 2, 3(unsign)
    * B's commitment transaction: HTLC: No.1,2(signed)
  * B have:
    * A's commitment transaction: HTLC: No.1, 2, 3(unsign)
    * B's commitment transaction: HTLC: No.1, 2(signed)
```

6. [B-->A]send `commitment_signed` (signature: A's commitment transaction(No.1,2,3 HTLC))
7. [A-->B]send `revoke_and_ack`

```
At this time:
  * A have:
    * A's commitment transaction: HTLC: No.1, 2, 3(signed)
    * B's commitment transaction: HTLC: No.1,2(signed), No.3(unsign)
  * B have:
    * A's commitment transaction: HTLC: No.1, 2, 3(signed)
    * B's commitment transaction: HTLC: No.1, 2(signed), No.3(unsign)
```

8. [A-->B]send `commitment_signed` (signature: B's commitment transaction(No.1,2,3 HTLC))
9. [B-->A]send `revoke_and_ack`

```
At this time:
  * A have:
    * A's commitment transaction: HTLC: No.1, 2, 3(signed)
    * B's commitment transaction: HTLC: No.1, 2, 3(signed)
  * B have:
    * A's commitment transaction: HTLC: No.1, 2, 3(signed)
    * B's commitment transaction: HTLC: No.1, 2, 3(signed)
```

Is it OK ??

**Comment by rustyrussell** [comment]
Yes, this is correct!  The protocol is quite complicated because it's so asynchronous.  Indeed, it requires three round trips for this case, as you've shown.

**Comment by nayuta-ueno** [comment]
@rustyrussell Thank you for your reply !
