### ISSUE TITLE
BOLT11: unable to tip

### ISSUE THREAD

**Issue by haarts** [lightningnetwork/lightning-rfc#479]
I'm creating a PoS app with a BTCPay backend. That app displays QR codes for the payer to scan, the QR code encodes a BIP21 or BOLT11 payment URL. It also lets the payer choose a tip (5%/10%/round up).
Currently the flow is:
- store owner enters amount to be paid
- app contacts the BTCPay server and creates an 'invoice' which contains all manners of payment URLs and what not
- app displays a QR code encoding one of the payment URLs
- the user can now pay or choose to add a tip
- if the user adds a tip the *app* modifies the payment URLs (and thus the QR code) with the updated amount

BIP21 allows for me to do this. I parse the BIP21 URL and modify the 'amount' query parameter. BOLT11 does *not* allow this because the amount is covered in the signature.

Obviously I could create a new invoice with the new amount. But this requires an other round trip to the backend which is inevitably slow. Beside that BTCPay will flag an invoice *overpaid* when more is paid than requested, this is nice for the user again. We show a big **thank you** when this is the case.

Of course there are all sorts of work-arounds for these issues. All of which are laborious and/or inelegant. 

I don't expect that the specification is changed. What I hope to accomplish is to raise awareness regarding on how people are using Lightning. 

This issue touches on issues raised in #324.

Side note: the QR code encoding a BOLT11 string is rather long compared to a BIP21, this is detrimental for the scanner.

**Comment by halseth** [comment]
I think you can just pay the BOLT-11 invoice with an amount larger than specified in the invoice?

**Comment by haarts** [comment]
You certainly can. Scan the QR code and, on the payer device, modify the amount. I am aiming for a smoother experience. I immediately concede there are obvious solutions for this, but I want the customer experience to be a natural and quick as possible. And changing the amount is an inconvenience, tapping a dedicated button less so.

**Comment by Roasbeef** [comment]
> But this requires an other round trip to the backend which is inevitably slow. 

200-300ms is slow?

**Comment by Roasbeef** [comment]
Seems the user can just overpay, and you detect that on the backend?

**Comment by haarts** [comment]
I would consider 200-300ms network latency almost a best case scenario. Then there's the work to be done on the server side and client side. The many situations the PoS is going to be deployed in will almost certainly yield longer wait times (a crowded restaurant for example).

The user can overpaid of course. But this would increase the amount of actions a users must perform significantly. Certainly an option but not desirable.

**Comment by rustyrussell** [comment]
@haarts Thanks for this feedback, it's certainly not something I've considerd before!

The real solution for this problem is a "includes tip amount" field in BOLT11.  That would cause wallets which understand it to prompt the user for a tip, with the suggestion filled in, and wallet which doesn't just pays the suggested amount.

However, I'm reluctant at this stage to add a bolt11 field for a niche use case; it's easy to add later and hard to remove.  So I'm going to close this for now; if we see significant demand, please revisit.
