### ISSUE TITLE
BOLT 3 : accepted_htlc_script expected weight shouldn't be 138 instead of 139 ?

### ISSUE THREAD

**Issue by ariard** [lightningnetwork/lightning-rfc#483]
Expected weight of accepted_htlc_script is evaluated at 139, but seems like the 32 number, 2nd operand of 2nd OP_EQUAL is by mistake set with a 2 bytes length. Shouldn't it be set to 1 byte and so accepted_htlc_script have instead a weight of 138 bytes ?

**Comment by ariard** [comment]
Ah sorry think @TheBlueMatt as the right explanation, but seems there is a lack of an OP_DATA which takes 1 byte in accepted_htlc_script description, a little bit confusing at first?

**Comment by rustyrussell** [comment]
@cfromknecht I think you might have some feedback on this?

**Comment by TheBlueMatt** [comment]
The spec could be clarified but technically (for mainnet bitcoin) it is correct.
