### ISSUE TITLE
BOLT-6 missing intentionally?

### ISSUE THREAD

**Issue by s-tikhomirov** [lightningnetwork/lightning-rfc#551]
[BOLT #0: Introduction and Index](https://github.com/lightningnetwork/lightning-rfc/blob/master/00-introduction.md) goes like this:

```
5. BOLT #5: Recommendations for On-chain Transaction Handling
6. BOLT #7: P2P Node and Channel Discovery
```

Is BOLT 6 skipped intentionally? Maybe add a clarification? For people downloading and printing the spec in one file for easier reading, the lack of BOLT 6 may give a false impression that they missed a  chapter.

**Comment by pm47** [comment]
BOLT 6 was about using IRC as a way to exchange network announcements. It has been superseded by BOLT 7 and removed from the spec with commit f91df05d1917386c1c77f8a386c4eb97d12e3154.
