### ISSUE TITLE
Access to the minutes of the IRC meetings?

### ISSUE THREAD

**Issue by OrfeasLitos** [lightningnetwork/lightning-rfc#568]
Are the minutes public? If so, where can we find them?

**Comment by araspitzu** [comment]
Hi the IRC channel is #lightning-dev @ freenode, you can find daily logs of the channel [here](http://gnusha.org/lightning-dev/) and you can usually find the meeting's minutes posted by 'lightningbot' at the end of the meeting. [Here are the minutes from the last meeting.](http://www.erisian.com.au/meetbot/lightning-dev/2019/lightning-dev.2019-02-04-19.00.html)

**Comment by OrfeasLitos** [comment]
Thanks!

**Comment by ysangkok** [comment]
Since this shows up in IRC search results, I'd like to note that recent minutes are at https://github.com/lightningd/meetings/tree/gh-pages
