### ISSUE TITLE
What is the threshold for to_self_delay to be unreasonably large? 

### ISSUE THREAD

**Issue by renepickhardt** [lightningnetwork/lightning-rfc#582]
In bolt 02 it is described that the recipient of a `open channel` message must fail the channel if `to_self_delay` is unreasonably large. 

Where did unreasonably start? I believe elswhere in the protocol we have 2016 blocks as the maximum timelock would that be the threshold here? If so, why not making it explicit?

**Comment by t-bast** [comment]
I think this is really a user choice and shouldn't be set in stone in the spec.
You unilaterally decide what value you want to reject for incoming channels.

For outgoing channels, the remote unilaterally decides what value it accepts; if your `open_channel` fails, it's your choice as a user to lower `to_self_delay` to accommodate what the remote wants, or if you find it unreasonable just don't open a channel with that peer.

Feel free to continue the discussion or re-open the issue if needed.
