### ISSUE TITLE
No way (according to LND dev wpaulino) to identify the network of a connection request.

### ISSUE THREAD

**Issue by dscotese** [lightningnetwork/lightning-rfc#600]
### Background

I use eclair on my desktop (sorry!) but I'm setting up lnd on a Lunanode server.  I wanted to see eclair report that I was trying to connect to a testnet node (my testnet node is 02fcc38fcbf0c4c467609870e7f177a6579515861de2e6e0ad4acaae3f33488834@172.81.183.236:9735) so I did a "simple connection" and that worked.  I expected it to fail with a "wrong network" message or something.  My eclair log does eventually show a ton of `message ChannelAnnouncement (pubIDs) for wrong chain` entries.  So eclair knows what's going on.

### Your environment
```
ubuntu@btc-ln:~/lnd$ lncli -n testnet getinfo
{
        "version": "0.6.0-beta commit=v0.6-beta-rc3-32-g7a0c9f33bc49c123024e0993e32154cae616ae8c",
        "identity_pubkey": "02fcc38fcbf0c4c467609870e7f177a6579515861de2e6e0ad4acaae3f33488834",
        "alias": "Test MemeracingLN",
        "num_pending_channels": 0,
        "num_active_channels": 0,
        "num_inactive_channels": 0,
        "num_peers": 0,
        "block_height": 1488977,
        "block_hash": "00000000144f76c6ad5aab8c74918a724aed4969779b2e435ff9f0547396ce67",
        "best_header_timestamp": 1533317365,
        "synced_to_chain": false,
        "testnet": true,
        "chains": [
                {
                        "chain": "bitcoin",
                        "network": "testnet"
                }
        ],
        "uris": [
                "02fcc38fcbf0c4c467609870e7f177a6579515861de2e6e0ad4acaae3f33488834@172.81.183.236:9735"
        ]
}
```

This may be a feature request, but it would make sense for any peer connection request to involve an identification of the network on which the requestor is operating. https://github.com/lightningnetwork/lnd/issues/2441 suggests to me that this is impossible to resolve without a change in the spec.

**Comment by t-bast** [comment]
Closing this issue, all implementations do offer indications about the network now.
