### ISSUE TITLE
BOLT-08: replace RFC 7539 with RFC 8439

### ISSUE THREAD

**Issue by ysangkok** [lightningnetwork/lightning-rfc#646]
There are [errata for RFC 7539](https://www.rfc-editor.org/errata_search.php?rfc=7539), and RFC 8439 claims that it is just RFC 7539 with the errata applied, and a new section. If this is indeed the case, all implementations should be conforming to RFC 8439, and the reference in BOLT-02 could be changed with no issues. This would make it easier for implementers since they wouldn't be confused by the errata.

**Comment by t-bast** [comment]
Fixed by https://github.com/lightningnetwork/lightning-rfc/pull/763
