### ISSUE TITLE
bolt11 encoding capital letters

### ISSUE THREAD

**Issue by sbtc1** [lightningnetwork/lightning-rfc#659]
The reference documentation does not mention the possibility of using a capitalised invoice (eg LNBC..), still most implementations in the wild seem to accept them.

There are good reasons to support capitalised invoices, like smaller QR codes. 

My suggestion is to explicitely mention in the documentation that invoices should be case-independant so that implementations must allow both forms (or even mixed).

**Comment by t-bast** [comment]
That sounds reasonable. Can you open a pull request to propose that change?

**Comment by rustyrussell** [comment]
Note that this is already specified in BIP-0173 which is heavily referenced, however I agree it's good to highlight it.
