### ISSUE TITLE
BOLT 1: Determining whether an error contains a valid string or not

### ISSUE THREAD

**Issue by donaloconnor** [lightningnetwork/lightning-rfc#68]
BOLT 1 describes the error message and the optional data field

> A receiving node SHOULD only print out data verbatim if it is a valid string.

How does one determine if the data is a valid string?
Besides a string, it's not obvious what this optional data field may contain or how it should be parsed.
I appreciate that this is probably going to be spec'd out in future revisions.

Thanks,
Donal

**Comment by cdecker** [comment]
I think this refers to the string being valid ASCII or UTF-8, otherwise it'll print junk on stdout or a UI. It's rather easy to verify, but we should probably specify what constitutes a valid string.
