### ISSUE TITLE
What are the preimages of the payment hashes of the Bolt11 Examples?

### ISSUE THREAD

**Issue by Sword-Smith** [lightningnetwork/lightning-rfc#683]
The Bolt11 examples use payment hashes such as `000102...`. uint256 numbers for which the preimage is unknown. If people are writing software that verifies that the `payment_hash` is actually the `sha256(x)`, then it would be nice to include `x` in the breakdown of these invoices.

**Comment by t-bast** [comment]
Why would you care about preimages when testing invoice encoding?

The goal of the Bolts is to try to break the protocol into different components that can be as independent as possible (it's proving to be hard in many places, but at least that's the goal).

Bolt 11 is only about payment encoding. Thus the examples should how you encode and decode some sample invoices. Invoices know nothing about the payment preimage, so there's no reason to test that at this level.

**Comment by Roasbeef** [comment]
Yep, I can hand you a payment hash and you can create an invoice for that without you ever learning of the preimage.
