### ISSUE TITLE
Possible race condition(double spend) on HTLC-Timeout transactions?

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lightning-rfc#686]
From the offered HTLC Outputs,
```
# To remote node with revocation key
OP_DUP OP_HASH160 <RIPEMD160(SHA256(revocationpubkey))> OP_EQUAL
OP_IF
    OP_CHECKSIG
OP_ELSE
    <remote_htlcpubkey> OP_SWAP OP_SIZE 32 OP_EQUAL
    OP_NOTIF
        # To local node via HTLC-timeout transaction (timelocked).
        OP_DROP 2 OP_SWAP <local_htlcpubkey> 2 OP_CHECKMULTISIG
    OP_ELSE
        # To remote node with preimage.
        OP_HASH160 <RIPEMD160(payment_hash)> OP_EQUALVERIFY
        OP_CHECKSIG
    OP_ENDIF
OP_ENDIF
```
With the following conditions,

- a `locktime` is set to be 600900 in the HTLC-Timeout transaction.
- the remote node has the `payment_secret`.
- the local node wants to timeout the latest commitment transaction.

From my understanding, to timeout the latest commitment transaction, the local node has to,

1. broadcast the commitment transaction at blockheight 600900;
2. immediately broadcast the HTLC-Timeout transaction;
3. wait a few days to spend the HTLC-Timeout transaction once the specified timelock value has passed.

Meanwhile, the remote node with the `payment_secret` can spend the commitment transaction too. Will this cause a race condition/double spend in the Bitcoin network? If so, how can it be resolve?
#

**Comment by fiatjaf** [comment]
My guess: If the remote node really has the `payment_secret` and for some odd reason decided to only use it after local node have broadcasted the commitment transaction, that's still fine. Local node will see the `payment_secret` and use it to fulfill the HTLC on his other channel.

**Comment by Roasbeef** [comment]
> broadcast the commitment transaction at blockheight 600900;

No, they can broadcast _before_ then (the node that has the outgoing HTLC). Only after that height can they timeout the HTLC on chain. 

> Meanwhile, the remote node with the payment_secret can spend the commitment transaction too.

Only one spend can go into the chain. If the party with the incoming HTLC goes on-chain to pull it, and gets that confirmed before the timeout transaction, then the node that offered the HTLC can use that to settle _their_ incoming HTLC. The node straddling both HTLCs needs to mind the CLTV delta between the two HTLCs. This is where the actual race can arise: if the incoming HTLC _expires_ before the outgoing HTLC has been _timedout on chain_, then a partial settlement can occur.
