### ISSUE TITLE
Doubt from first example

### ISSUE THREAD

**Issue by atlaschiew** [lightningnetwork/lightning-rfc#687]
![Capture](https://user-images.githubusercontent.com/45816141/67565652-8611b180-f758-11e9-9490-e87897dbcbd0.JPG)
hi guys, please review my attachment. This is question referring to first example. I have been using a convertbit tool to convert 35 bits 1496314658 into 8 bits hex, as the result, i got 0b 25 fe 64 40 which is not match to 0b 25 fe 64 41 that provided in an example. Scratching my head :s

**Comment by nayuta-gondo** [comment]
>0b 25 fe 64 41

The last 5bits are `p`tag = 0b00001

**Comment by atlaschiew** [comment]
> > 0b 25 fe 64 41
> 
> The last 5bits are `p`tag = 0b00001

thanks nayuta, i get it
