### ISSUE TITLE
Setting channel closure fee in manual way

### ISSUE THREAD

**Issue by bitcoin-software** [lightningnetwork/lightning-rfc#702]
Reffering to this question: https://bitcoin.stackexchange.com/questions/91755/private-agreement-between-two-c-lightning-nodes-on-channel-closure-fee

> When i was at LNConf, one of the devs of c-lightning (IIRC) told me that there is a custom, manual way to agree between two nodes on channel closing fees.
> Can anyone elaborate how this is possible? I am operator of two cln nodes, i would like to close channel between these nodes with minimum possible fee, because i am not in hurry.
> Are there some side-effects of doing so?

>  I dont want to wait until mempool clears to perform tx. i just want to broadcast it and lay back, so it will be included, when mempool clears. so i dont need to monitor state of mempool

Would like to hear your thoughts.

**Comment by Roasbeef** [comment]
Seems this issue should live in the c-lightning issue tracker. The way fees are specified for channel closing at the end points is an implementation detail. Most nodes provide an argument when closing a channel to express what your ideal fee is. In the protocol there's a very loosely defined negotiation that should take place between both parties to decide on the final fee. It may be the case that you end up paying a little bit higher than what you specify, depending on how the implementations handle the fee negotiation.
