### ISSUE TITLE
Meeting to discuss anchor outputs

### ISSUE THREAD

**Issue by t-bast** [lightningnetwork/lightning-rfc#706]
Placeholder issue to organize a meeting (hangout / zoom / skype / whatever you'd like as long as we can actually speak) to discuss anchor outputs in a more productive way.

@TheBlueMatt @rustyrussell @niftynei @Roasbeef @sstone @joostjager @halseth 

Please start by adding other people that would be interested in joining the call and we can submit dates/time proposals.

**Comment by jonatack** [comment]
I've been following these discussions and would enjoy joining the call to listen.

**Comment by rustyrussell** [comment]
5:30 am until 7am Adelaide time works best for me.  Here's an example SF/Berlin/Adelaide crossover:

https://www.timeanddate.com/worldclock/meetingtime.html?day=4&month=12&year=2019&p1=5&p2=37&p3=224&iv=0

**Comment by t-bast** [comment]
This was discussed during yesterday's meeting.
The recording will be made available shortly.
