### ISSUE TITLE
BOLT-01: difference between "stop" and "fail"?

### ISSUE THREAD

**Issue by yyforyongyu** [lightningnetwork/lightning-rfc#715]
Need a bit clarification on BOLT-01, line 139, here's the quote,

> The receiving node:
> - if zero bytes remain before parsing a `type`:
>   - MUST **stop** parsing the `tlv_stream`.
> - if a `type` or `length` is not minimally encoded:
>   - MUST **fail** to parse the `tlv_stream`.
>...

What's the difference between a `MUST stop` and `MUST fail`?

**Comment by t-bast** [comment]
Stop means the same as reaching EOF: this is a "success" stop. You return to your application layer the tlv records you were able to decode.
 
Fail means you should throw away the whole `tlv_stream` as invalid (even if you parsed a few valid tlv records out of it).

**Comment by t-bast** [comment]
Closing this issue, feel free to re-open if the answer wasn't clear enough.
