### ISSUE TITLE
Preventing overly small MPP chunks

### ISSUE THREAD

**Issue by btcontract** [lightningnetwork/lightning-rfc#721]
An MPP sender may divide a payment into overly small chunks, such that each individual chunk is either not redeemable on-chain due to fee levels or at least loses too much value. 

Receiver's peer may then break a channel(s) once preimage is revealed, by doing this they will only lose those channels, but receiver will also lose a whole payment.

Receiver may reject a payment right away if an overly small chunk arrives, but then a sender should somehow know receiver's limits to not send such chunks in a first place.

**Comment by t-bast** [comment]
Thanks for reporting this.

@rustyrussell @cfromknecht should the rule be: "a receiver SHOULD not accept partial HTLCs below the dust limit" or something like that? It's fine for an HTLC set with a single HTLC to be below the dust limit, but if you're using multiple HTLCs then it's dangerous.

Or maybe just a recommendation to implementers to watch out for this, but without providing a hard rule?

**Comment by btcontract** [comment]
I want to add that losing an entire payment is of course a terminal case, but receiver may still not want to lose, say, 50% of sum by redeeming many chunks on-chain, so perhaps an acceptable limit should somehow be calculated by receiver and sent to sender (tag in payment request, "chunk too small" onion error?).

**Comment by t-bast** [comment]
We discussed this during yesterday's meeting, you can find the full logs here: http://www.erisian.com.au/meetbot/lightning-dev/2020/lightning-dev.2020-01-06-19.18.log.html

The overall feeling is that this can be easily avoided by correctly configuring your node for your usecase.
Merchants should configure `htlc-minimum-msat` and `max-htlcs-in-flight` with sane values to avoid this (especially `htlc-minimum-msat` that can easily be set above the dust level).
This is a best practice we need to make sure merchants are aware of, but doesn't need a spec update.
