### ISSUE TITLE
BOLT 04: tlv_payload description is not clear

### ISSUE THREAD

**Issue by bitonic-cjp** [lightningnetwork/lightning-rfc#800]
First of all, apparently TLV stands for Type Length Value, which was not immediately obvious to me. I guess the format is a sequence of one or more {type, length, value} fields - it would be nice to specify this explicitly.

Secondly, it doesn't specify the size of the type and length fields. Since earlier text claims that the minimum `tlv_payload` length is two bytes, I guess that's one byte for type, one byte for length and zero bytes for value (if length == 0)? If I need to guess, it's an indication the spec lacks some clarity.

**Comment by t-bast** [comment]
Does the section [here](https://github.com/lightningnetwork/lightning-rfc/blob/master/01-messaging.md#type-length-value-format) answer these questions?

We may be missing a link from bolt 4 to bolt 1 to reference that section, feel free to add one where it would have made sense for you.

**Comment by cdecker** [comment]
I think this can be closed?
