### ISSUE TITLE
Confusion about the HTLC

### ISSUE THREAD

**Issue by ZhichunLu-11** [lightningnetwork/lightning-rfc#806]
I'm a learner of lightning networks, but I'm a little confused about the HTLC, so let's start with "Flood & Loot". This is an attack on HTLC, and the core idea is to destroy its atomicity through a lot of on-chain HTLC disputes. Among other things, it is described in his paper as follows

>Although HTLC outputs can be claimed by the victims even after they expire, the attacker has a significant advantage at that point. In order to replace victims’ transactions, the attacker must publish his transactions with higher fees. The attacker knows exactly what fee is used by his victims (this is derived from the channel’s feerate) and can easily create transactions with the minimal fee required to outcome those of the victims. The HTLC-timeout used by the attacker should only be signed by him, and he can set the fee as he wishes. In contrast, the HTLC-success used by the victims must be signed by both parties (and was in fact already signed when the HTLC was added), and therefore cannot be changed by the victim to pay more fees, without the cooperation of the attacker.
The reason the attacker only needs his signature, while victims need both their signatures and that of the attacker, is that the published commitments are those of the victims. Contrarily, if the attacker’s commitment was the one to be published and confirmed, the attacker would have to use pre-signed transactions, while the victims could have claimed HTLC outputs without the attacker’s signature. Of course, in this attack, the victims have no choice but to publish their commitments before expiration, if they want to claim their funds.

Is this true in LND? From my naive perspective, regardless of who submits the commitment transaction with HTLC, both parties can use their own keys to construct the transaction that unlocks HTLC. For example, I think the lock is something like

```
Alice pubkey + CLTV time lock
or
Bob pubkey + preimage
```

I'm confused as to why for the party submitting the commitment, he has to have signatures from both parties if he wants to unlock the HTLC.

Also, I was looking at your source code recently and it's very well written with lots of comments, which helps me a lot. But while reading the function [SignNextCommitment](https://github.com/lightningnetwork/lnd/blob/master/lnwallet/channel.go#L3506), I found that the function requires each node to sign each HTLC and I'm very confused about this, which seems to be the same thing as described in that paper. If you can answer my confusion, I'd appreciate it!

**Comment by t-bast** [comment]
You can have a look at Bolt3 or https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md to get you started on these.
Note that if you have questions about specific code in lnd, please move the issue to their repo instead of this spec repo.

**Comment by ZhichunLu-11** [comment]
> You can have a look at Bolt3 or https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md to get you started on these.
> Note that if you have questions about specific code in lnd, please move the issue to their repo instead of this spec repo.

First of all, thank you very much, I seem to have figured out the principle of it, but I still want to confirm it with you.

Actually, with either HTLC-timeout or HTLC-success, the submitter does not get their own money back immediately but has to wait for a period of time, which is used to ensure that if I submit an outdated commitment, then the other party can use the revocation key to take all the HTLC money.

So, to avoid users building HTLC-success and HTLC-timeout that get refunds immediately. the HTLC output in the commitment needs two signatures to unlock it.

**Comment by t-bast** [comment]
>  which is used to ensure that if I submit an outdated commitment, then the other party can use the revocation key to take all the HTLC money.

That's exactly it.

> So, to avoid users building HTLC-success and HTLC-timeout that get refunds immediately. the HTLC output in the commitment needs two signatures to unlock it.

Yep!

**Comment by Roasbeef** [comment]
Closing as seems the question was answered?
