### ISSUE TITLE
cltv_expiry_delta definition

### ISSUE THREAD

**Issue by ZhichunLu-11** [lightningnetwork/lightning-rfc#822]
While reading the [RFC](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#cltv_expiry_delta-selection), I had a problem with the definition of the section cltv_expiry_delta. I note the following statement.

```
Worst case: There's reorganization R deep in which C wins and fulfills. B only sees transaction at N+G+S+R.
```

I'm very confused, are there two transactions involved here? One is a commitment transaction and the other is a unlock HTLC transaction. So should it be 2*(R+S) here?

**Comment by t-bast** [comment]
Yes there are two transactions involved: the commitment transaction and then the HTLC-timeout transaction.
See [Bolt 3](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md) and [Bolt 5](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md) for details, or https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md for a more high-level introduction.

**Comment by ZhichunLu-11** [comment]
> Yes there are two transactions involved: the commitment transaction and then the HTLC-timeout transaction.
> See [Bolt 3](https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md) and [Bolt 5](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md) for details, or https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md for a more high-level introduction.

Yes, but my question is why I submitted two transactions, but I only had to wait for R+S+G time to confirm they are on-chain and irreversible.
I think they first have to compete for the on-chain chance of the commitment transaction, which will take R+S blocks.
They will then compete for the right to submit HTLC settlement transactions, which will take another R+S blocks to be confirmed. Is it right?

**Comment by t-bast** [comment]
No, you only compete for the HTLC transaction.
You're not competing for "the right to submit", you're competing for confirming conflicting transactions.

**Comment by ZhichunLu-11** [comment]
> No, you only compete for the HTLC transaction.
> You're not competing for "the right to submit", you're competing for confirming conflicting transactions.

Isn't there competition between commitments? I remember that the two parties in RSMC hold different commitments. 

For example, I submitted the commitment_A and the HTLC transaction to refund it. But unfortunately the other party's commitment_B has priority. So I need to wait until I see that the comment_B has been on-chain, and I need to rebuild the HTLC transaction to unlock the HTLC-UTXO in commitment_B.

This is my understanding, but of course I may be wrong about it... Please let me know if there are any errors. I'd appreciate it!

**Comment by ZhichunLu-11** [comment]
And I also notice that definition of `R` and `S`
```
a worst-case reorganization depth R blocks
a number of blocks S between transaction broadcast and the transaction being included in a block
```
This should be applicable to any transaction, right? Even if a transaction does not have any conflicting one, it still needs to go through the time of being broadcast and the time of on-chain confirmation.

**Comment by t-bast** [comment]
In that sense there is indeed competition between the two commitment txs, but I think you're conflating two unrelated problems.
This section only explains how you should choose the timeout delta for HTLC.

This is completely unrelated to the race between commitment txs: the assumption is made here that a commitment tx (you don't care which one) will be confirmed before S blocks. Once it's confirmed, you simply broadcast the right HTLC transaction depending on what commit tx confirmed.

**Comment by ZhichunLu-11** [comment]
> In that sense there is indeed competition between the two commitment txs, but I think you're conflating two unrelated problems.
> This section only explains how you should choose the timeout delta for HTLC.
> 
> This is completely unrelated to the race between commitment txs: the assumption is made here that a commitment tx (you don't care which one) will be confirmed before S blocks. Once it's confirmed, you simply broadcast the right HTLC transaction depending on what commit tx confirmed.

Yes, as you said, in N+S+G+R we only know the commitment is on the chain, and then both sides can unlock the HTLC in their own way.  But in the RFC
```
3. Worst case: There's reorganization R deep in which C wins and fulfills. B only sees transaction at N+G+S+R.
4. B now needs to fulfill the incoming A->B HTLC, but A is unresponsive: B waits G more blocks before giving up waiting for A. A or B commits to the blockchain.
```

I think for B, he must know clearly whether the HTLC between BC terminates with a refund or with payment completion at step4. However, in our discussion

N+S+R+G: we know which commitment is on-chain.
N+S+R+G+S+R: we know how the HTLC is settled.

It is clear that B cannot respond to A when N+S+R+G.

**Comment by ZhichunLu-11** [comment]
I think the worst case scenario would be. (I omitted grace period `g` for simplicity.)

N+S+R: 
1. Commitment between B and C is on-chain. 
2. Commitment between A and B is broadcasted.

N+2*(S+R): 
1. HTLC between BC is settled.
2. B begins to broadcast HTLC-unlock transaction in AB.

N+3*(S+R): 
1. HTLC between AB is settled.

**Comment by t-bast** [comment]
No, I think that you're still conflating these two issues.
Remember that `N` is the block at which the HTLC times out.
The HTLC sender will publish his commitment transaction before N is reached, to ensure the commitment transaction is confirmed before the HTLC can be settled. You don't need to count additional `S` and `R` for it.

**Comment by ZhichunLu-11** [comment]
> No, I think that you're still conflating these two issues.
> Remember that `N` is the block at which the HTLC times out.
> The HTLC sender will publish his commitment transaction much before N is reached, to ensure the commitment transaction is confirmed before the HTLC can be settled. You don't need to count additional `S` and `R` for it.

I don't think this is the case, or that the definition in RFC is wrong.

The definition of G

```
a grace-period `G` blocks after HTLC timeout before giving up on an unresponsive peer and dropping to chain
```

**Comment by ZhichunLu-11** [comment]
> No, I think that you're still conflating these two issues.
> Remember that `N` is the block at which the HTLC times out.
> The HTLC sender will publish his commitment transaction much before N is reached, to ensure the commitment transaction is confirmed before the HTLC can be settled. You don't need to count additional `S` and `R` for it.

Well, is there something wrong with my understanding 😂? I re-read the RFC and I don't find any discussion elsewhere about when to submit commitment. If you know where there is information on this and can tell me, I'd appreciate it!

Secondly, according to your description,  the definition of grace period here is incorrect... or did I misunderstand something?

**Comment by t-bast** [comment]
Hopefully a more visual diagram will make this clearer.
I wanted to do a piece on that in https://github.com/t-bast/lightning-docs but didn't find the time yet.

Suppose we have a payment `A -> B -> C` as described in Bolt 2:

```ascii
    htlc1        htlc2
A ---------> B ---------> C
```

Where the `cltv_expiry_delta` of the channel `B -> C` is 144 blocks.
That means we the htlc expiries will be something like:

* htlc1 expires at block 1144
* htlc2 expires at block 1000

The gist of this Bolt 2 section tries to explain that part of the 144 blocks are "allocated" so that Bob is able to ensure that htlc2 is fully settled (either on-chain or off-chain) and fulfill htlc1 on-chain before it reaches its expiry if Bob learnt the preimage from C. I've called this duration `fulfill_safety_delta` and it kinda captures in a simplified way the important aspect of this spec section.

You can think of it this way:

```ascii
 received htlc expiry (1144)                            offered htlc expiry (1000)
            |                                                     |
            |                                                     |
            v                                                     v
            +-----------------------------------------------------+
                               cltv_expiry_delta
            <----------------------------------------------------->
                fulfill_safety_delta
            <---------------------------><------------------------>
```

It's explained a bit more here, even though the main topic is something entirely different: https://github.com/t-bast/lightning-docs/blob/master/lightning-txs.md#alternative-proposal

**Comment by ZhichunLu-11** [comment]
So what you're trying to say is: what's in Bolt2 actually explains the composition of fullfill_safety_delta (part of cltv_expiry_delta)?

But it's strange that Bolt2 uses the name "cltv_expiry_delta". I'm still very confused because your statement seems to be inconsistent with the one in Bolt2.

**Comment by ZhichunLu-11** [comment]
Sorry, I think there seems to be a bit of misunderstanding I haven't sorted out. what transactions does B send when it expires? No doubt he needs to submit commitment_B as well as Htlc_refund_B (HTLC refund transaction for consuming commitment_B), but will he send Htlc_refund_C?

**Comment by t-bast** [comment]
> So what you're trying to say is: what's in Bolt2 actually explains the composition of fullfill_safety_delta (part of cltv_expiry_delta)?

What's in Bolt 2 explains the composition of `cltv_expiry_delta`, but the "tricky" part of that composition is what I'm calling `fulfill_safety_delta` (that's the part that's in practice most important for security). This is my personal notation, other implementers may view it differently.

> what transactions does B send when it expires?

It's important to distinguish what happens in the channel `B -> C` and what happens in the channel `A -> B`.
What `B` broadcasts depends on the scenario: `B` broadcasts a transaction when an HTLC is at risk and isn't being settled off-chain.

The subtle scenario is when `htlc2` was fulfilled by `C` (`B` knows the preimage), `B` tries to fulfill it with `A`, but `A` plays dead. `B` cannot wait for too long, because if `htlc1` times out, `A` could get their funds back with an on-chain transaction and `B` would lose money (because he paid `C`). So `B` has to publish the commit-tx for the channel `A -> B` and his htlc-success tx and get it to confirm during his `fulfill-safety-delta`, so that `A` cannot have the opportunity to cheat.

**Comment by ZhichunLu-11** [comment]
> > So what you're trying to say is: what's in Bolt2 actually explains the composition of fullfill_safety_delta (part of cltv_expiry_delta)?
> 
> What's in Bolt 2 explains the composition of `cltv_expiry_delta`, but the "tricky" part of that composition is what I'm calling `fulfill_safety_delta` (that's the part that's in practice most important for security). This is my personal notation, other implementers may view it differently.
> 
> > what transactions does B send when it expires?
> 
> It's important to distinguish what happens in the channel `B -> C` and what happens in the channel `A -> B`.
> What `B` broadcasts depends on the scenario: `B` broadcasts a transaction when an HTLC is at risk and isn't being settled off-chain.
> 
> The subtle scenario is when `htlc2` was fulfilled by `C` (`B` knows the preimage), `B` tries to fulfill it with `A`, but `A` plays dead. `B` cannot wait for too long, because if `htlc1` times out, `A` could get their funds back with an on-chain transaction and `B` would lose money (because he paid `C`). So `B` has to publish the commit-tx for the channel `A -> B` and his htlc-success tx and get it to confirm during his `fulfill-safety-delta`, so that `A` cannot have the opportunity to cheat.

Thank you very much for your patience, and one small question. If Bob submits commitment and Htlc_Success, then both transactions will be included in the block within `S` blocks, right? (`S` is the time from when a transaction is broadcast to when it is included in the block).

**Comment by t-bast** [comment]
> If Bob submits commitment and Htlc_Success, then both transactions will be included in the block within S blocks, right?

Yes exactly.
