### ISSUE TITLE
BOLT 2: Does not specify how to "generate" point from per_commitment_secret

### ISSUE THREAD

**Issue by LLFourn** [lightningnetwork/lightning-rfc#832]
There are two ways to produce a point from a 32 byte secret:

1) reduce-then-multiply: interpret the 32-bytes as a big endian integer and reduce the result modulo the curve order and then multiply.
2) check-then-multiply: error if the 32-bytes as a big endian integer is greater than the curve order. Otherwise multiply.

Which does BOLT 2 mean mean when it says:
> if per_commitment_secret does not generate the previous per_commitment_point:
>    MUST fail the channel.

BIP32 specifies (1) but I noticed [rust-lightning does (2)](https://github.com/rust-bitcoin/rust-lightning/blob/b2f13275366146ce57a90d7eee1adce0ad119ce6/lightning/src/ln/channel.rs#L2237) because rust-secp256k1 only seems to [expose the API](https://docs.rs/secp256k1/0.20.0/secp256k1/key/struct.SecretKey.html) for (2) (I think libsecp256k1 has a public API for either).
I am not sure if BIP32 implementations actually stick to (1) though -- it is computationally infeasible to find a distinguishing case.

However in lightning the other party sends you the derived key (before you can even necessarily check that it is derived correctly) so the same rule doesn't apply.
This is not a security issue as long as implementations are consistent in which one they do. However it could be used to fingerprint a node's implementation so I guess it's best to specify one or the other.

**Comment by t-bast** [comment]
Interesting, I always assumed everyone did (1).
(2) only seems useful to guarantee constant time operations, right? Or is there another reason?

**Comment by LLFourn** [comment]
(2) is not preferable for any reason in this case I think.  But I think I am wrong in what I said about libsecp256k1. It looks like it only exposes (2): https://github.com/bitcoin-core/secp256k1/blob/f2d9aeae6d5a7c7fbbba8bbb38b1849b784beef7/include/secp256k1.h#L573

This means that everyone is probably doing (2) actually.

**Comment by rustyrussell** [comment]
IIUC it's about 1 in 2^128 chance of this happening randomly.  And since you're supposed to generate these points by hashing a seed (though you can send us a revoke_and_ack which doesn't do that), it's only important that the receiver correctly reject the value if it's not possible to generate the point.

So perhaps we should base it on the libsecp256k1 language?  "Is not a valid secret key or does not generate the public key equal to the previous per_commitment_point"?
