### ISSUE TITLE
Confusion about opaque reason

### ISSUE THREAD

**Issue by ZhichunLu-11** [lightningnetwork/lightning-rfc#855]
According to the description in [Bolt4](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#removing-an-htlc-update_fulfill_htlc-update_fail_htlc-and-update_fail_malformed_htlc), if a payment fails due to insufficient balance in an intermediate node. Then an Opaque reason containing Insufficient_balance is returned. According to the description, this information can only be decrypted by the payer. I'm curious how this is achieved. A simple idea is that the intermediate node uses the pubkey of the payer to encrypt it. But the intermediate nodes should be agnostic to the identity of the payer. So how is this achieved? Is it that the payer generates a pubkey unrelated to its own identity specifically for the intermediate nodes to use?

**Comment by t-bast** [comment]
The construction is detailed in the Sphinx paper: https://cypherpunks.ca/~iang/pubs/Sphinx_Oakland09.pdf
It's also described in Bolt 4: https://github.com/lightningnetwork/lightning-rfc/blob/master/04-onion-routing.md#packet-construction

But the spec version is quite concise and not always hard to grasp at first, so I detailed it more here: https://github.com/t-bast/lightning-docs/blob/master/sphinx.md

Looking at actual code and tests implementing this (in any lightning implementation) can also be helpful to understand the details.

**Comment by ZhichunLu-11** [comment]
Thanks
