### ISSUE TITLE
Are 483 max_accepted_htlcs one-way or two-way?

### ISSUE THREAD

**Issue by ZhichunLu-11** [lightningnetwork/lightning-rfc#861]
In BOLT2 the author describes the max_accepted_htlcs size as being recommended to be set to 483, my question is whether the value is the number of htlcs that one side of the channel can offer to the other or the sum of the htlcs that both sides can offer.

**Comment by fluxdeveloper** [comment]
Hi. This limit is unidirectional, and hence each party sets their own `max_accepted_htlc` in their open/accept channel message.

The rationale is given in [BOLT #5](https://github.com/lightningnetwork/lightning-rfc/blob/master/05-onchain.md#penalty-transactions-weight-calculation), and is a consequence of the maximum bitcoin transaction size.
