### ISSUE TITLE
Allow peers to announce "my side is empty, don't use" (voluntary, by tweaking channel policy)

### ISSUE THREAD

**Issue by C-Otto** [lightningnetwork/lightning-rfc#871]
I'm concerned about situations where my side of a channel is (mostly) empty, so that (most) forwardings through this channel would fail. Of course, I'd love to receive funds through that channel, as this would make the channel usable in both directions.

Currently, as a node operator, I have several options (aside from rebalancing the channel):

1. Do nothing. The channel will be included in payments, and these will fail. The reputation of my node will suffer.
2. Disable my side of the channel. In addition to the positive effects of this information, nodes might think that the channel is in a bad state. For example, nodes might think that the channel is unusable in both directions because the peer is offline (which, I think, is perfectly valid reason for me to set my local disable flag).
3. Raise the fee rate / base fee / min HTLC. Depending on the values used, this could still attract forwardings which will fail. Peers (or "ranking websites") might complain because I often change fees. Very high fees will raise my average/median, which again might hurt my node's reputation.

It would be great to have a dedicated flag ("I cannot send, but I'd be happy to receive!"), but I guess this isn't worth the effort. Maybe it is possible to weave this information into the existing policy parameters? "If the fee rate is a prime number and the base fee is the first digit of the fee rate's SHA256 hash..." or something less awkward might help.

Thanks to @alexbosworth for suggesting this ("Maybe we should start hacking the policy values to include these signals")

A similar flag/feature that would disallow incoming transactions would also be great.

**Comment by t-bast** [comment]
This is exactly one of the reasons why the `disable` bit exists and solution 2. should be the preferred way of signaling this. I don't see why we would need to add anything new to handle this case.

> nodes might think that the channel is in a bad state. For example, nodes might think that the channel is unusable in both directions because the peer is offline

Why would nodes think that the channel is in a bad state? What you may need is an implementation change, not a spec one, if your implementation penalizes such channels durably. Implementations should simply remove the channel from the routing graph while it's disabled, and re-add it once it's enabled, and they have no reason to penalize the nodes.

If you have:

```
A -----> B -----> C
```

And B is offline, both A and C will mark their channel as `disabled` on their side so B is effectively unreachable, and you don't need to penalize A or C for it, you can easily infer that B is down (if all channels pointing to it are becoming disabled).

**Comment by C-Otto** [comment]
I agree that it is a matter of interpretation, and changing the interpretation of how "bad" a disabled bit might be good enough. However, I can understand the following reasoning:

"I see the channel A <-> B. I also see that A disabled the channel, while the channel is still enabled from B. Without further knowledge (I'd have to look at C?), I do not know if B is online and able to send funds to A, or if B is offline and, thus, the channel cannot be used at all. To play safe, I just mark the channel as "bad" and exclude it from my routing attempts."

The scenario above is my main concern, and if I understood Alex correctly, he prefers to think/act as in this scenario. I'd like the spec to allow node A/B to signal "please use the channel, but only from B to A". Currently, it is not possible to communicate this without being ambigous.

Furthermore, in the scenario you described, you need nodes A and C to correctly communicate the channel state in order to draw the conclusion. I don't know if C (and other peers of B) behave in a way that allows external evaluators to draw conclusions about B (and the channel A <-> B).

**Comment by t-bast** [comment]
> I do not know if B is online and able to send funds to A, or if B is offline and, thus, the channel cannot be used at all. To err on the side of caution, I just mark the channel as "bad" and exclude it from my routing attempts.

> The scenario above is my main concern, and if I understood Alex correctly, he prefers to err on the side of caution as explained in this scenario.

But that scenario doesn't make sense, it will never happen. If B is offline, all channels *leading to it* will be disabled, so you don't even need to care about the channel `B -> A` because there will be no edge leading to B in your graph anyway, so no way of including this channel in a route.

**Comment by C-Otto** [comment]
I'm concerned about B being online, though...
