### ISSUE TITLE
feature nomeculture 

### ISSUE THREAD

**Issue by LightningHelper** [lightningnetwork/lightning-rfc#890]
Hi,
Not sure where I could ask it, so I hope here is ok.

I wonder is there is some specification/list on what features each implementation use to advertise itself.
I see so many different feature values (e.g. 8000000802aaa2, 8a52a1, 0a52a1...) for the different nodes and I don't know exactly how can I know what feature each implementation use. 

Also, some node don't advertise any feature.
Maybe there could be a list in this GitHub that will be updated by each implementation?

Thanks

**Comment by t-bast** [comment]
That wouldn't make sense, most implementations let the node operator configure what features it wants to activate.
You can try to fingerprint implementations from their *default* activated features (even though that changes depending on which version of the software node operators are running) but that doesn't work once node operators start customizing their node (which they should).

You shouldn't try to figure out which implementation a node is running, this can at best use heuristics that are easily defeated or broken at each software release. And this isn't an information that should be relevant, you only need to know what features a node supports to decide whether you want to connect to it or not - you shouldn't care about what implementation they're running.
