### ISSUE TITLE
New BOLT 11 Test cases are missing payment secret feature

### ISSUE THREAD

**Issue by TheBlueMatt** [lightningnetwork/lightning-rfc#897]
https://github.com/lightningnetwork/lightning-rfc/commit/42bd71d49c68075f54a31558af67af8c9892a08f added payment secret fields to invoice tests, but didn't add the payment_secret feature flag to them, causing them to be invalid according to the old rules and largely nonsensical as they don't have a feature set for a field they use. We should probably add the payment secret feature flag to them.

**Comment by t-bast** [comment]
Daaaamn...good catch, I'll fix that!
