### ISSUE TITLE
BOLT 3: Appendix B: Transactions Test Vectors invalid keys?

### ISSUE THREAD

**Issue by rustyrussell** [lightningnetwork/lightning-rfc#90]
local_funding_key: 30ff4956bbdd3222d44cc5e8a1261dab1e07957bdac5ae88fe3261ef321f374901
    remote_funding_key: 1552dfba4f6cf29a62a0af13c8d6981d36d0ef8d61ba10fb0fe90da7634d7e1301
    local_revocation_key: 131526c63723ff1d36c28e61a8bdc86660d7893879bbda4cfeaad2022db7c10901
    local_payment_key: e937268a37a774aa948ebddff3187fedc7035e3f0a029d8d85f31bda33b02d5501
    remote_payment_key: ce65059278a571ee4f4c9b4d5d7fa07449bbe09d9c716879343d9e975df1de3301

None of these are valid keys; they should start with 03 or 02, and why do they all end in 01?

The names also don't match the names in the rest of the document, but I was hoping to figure that out from the test vectors and submit a patch...

**Comment by sstone** [comment]
Ah yes, the names are confusing sorry about that: these are private keys serialized with the bitcoin convention of adding an extra 01 at the end to tag them as "compressed private keys" (i.e the public keys derived from these private keys are compressed). I will submit a patch.

**Comment by rustyrussell** [comment]
Ah, OK, that makes much more sense!

**Comment by rustyrussell** [comment]
Closed by #99
