### ISSUE TITLE
Enable Travis-CI for this repo

### ISSUE THREAD

**Issue by cdecker** [lightningnetwork/lightning-rfc#93]
We added the extraction tool as a travis-ci config, but we still need a repo admin to flip the switch:

https://travis-ci.org/profile/lightningnetwork

That should get us feedback on the extractor tool for all pull requests and allow formatting checks in the future.

**Comment by Roasbeef** [comment]
The switch has been flipped 👍

**Comment by cdecker** [comment]
Great, seems to be working :+1:
